#index:
#    path: /
#    controller: App\Controller\DefaultController::index

epodsone_backoffice:
    resource: '../src/Routing/backoffice.yaml'
    prefix: /dashboard

epodsone_website:
    resource: '../src/Routing/routing.yaml'
    prefix: /